AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '100'
    ConstraintDescription: must be between 1 and 100
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '100'
    ConstraintDescription: must be between 1 and 100
Resources: 
  dummyTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: partition_key
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: S
      KeySchema: 
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'
      TableName: 'dummyTable'
