name: Call Workflow

on: 
  push: 
    branches: [feature-test]
  pull_request:
    branches: [feature-test]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Release'
        type: string
        required: true

jobs:
  checks:
    runs-on: ubuntu-18.04
    name: Checks
    steps:
      - run: echo 'This is the first job'
  edge-deployment:
    needs: checks
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    uses: viyahe/continuous-platform/.github/workflows/reusable-deployment.yml@feature-test
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ${{ secrets.EDGE_DEPLOYMENT_NAME }}
      AWS_REGION: ${{ secrets.EDGE_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EDGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EDGE_AWS_SECRET_ACCESS_KEY }}
  feature-test-deployment:
    needs: checks
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature-test' }}
    uses: viyahe/continuous-platform/.github/workflows/reusable-deployment.yml@feature-test
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ''
      AWS_REGION: ${{ secrets.EDGE_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EDGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EDGE_AWS_SECRET_ACCESS_KEY }}