# This is a reusable workflow - check main-workflow for the integration
name: Deployment Workflow

on: 
  workflow_call:
    inputs:
      has-node:  
        description: does repo has node
        default: false
        type: boolean
        required: false
      has-python:
        description: does repo has python 
        default: false
        type: boolean
        required: false
    secrets:
      SSH_KEY:
        required: true
      DEPLOYMENT_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install AWS CDK
        run: npm install -g aws-cdk 

      - name: Setup ssh key for git
        uses: viyahe/actions/setup-ssh-key@v1
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Install Dependencies (pipfile)
        if: inputs.has-python
        uses: viyahe/actions/pipenv-install@v1

      - name: Install Dependencies (npm)
        if: inputs.has-node
        uses: viyahe/actions/npm-install@v1

      - name: Print AWS Creds
        run: |
          echo ${{ secrets.AWS_REGION }}
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        run: |
          cdk deploy --all -c deployment_name=${{ secrets.DEPLOYMENT_NAME }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}