# This is a reusable workflow - check main-workflow for the integration
name: Linters Workflow

on:
  workflow_call:
    inputs:
      has-node:
        description: does repo has node
        default: false
        type: boolean
        required: false
      has-python:
        description: does repo has python
        default: false
        type: boolean
        required: false
    secrets:
      SSH_KEY:
        required: true

jobs:
  linters:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Linters
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dependencies (pipfile)
        if: inputs.has-python
        uses: viyahe/actions/pipenv-install@v1

      - name: Install Dependencies (npm)
        if: inputs.has-node
        uses: viyahe/actions/npm-install@v1

      - name: Run linters
        if: inputs.has-python
        run: |
          pipenv run black
          pipenv run gitlint
          pipenv run pylint
          pipenv run pydocstyle

      - name: Run Eslint
        if: inputs.has-node
        run: yarn lint
