name: CI/CD Workflow

on: 
  push: 
    branches: [feature-test, develop, staging, acceptance, release/**]
  pull_request:
    branches: [feature-test, develop, staging, acceptance, release/**]
  workflow_dispatch:
    inputs:
      deployment:
        description: 'Release Manager Password'
        type: String
        required: true

jobs:
  linters:
    uses: ./.github/workflows/linters-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
  test:
    uses: ./.github/workflows/test-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  feature-test-deployment:
    needs: [linters, test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature-test' }}
    uses: ./.github/workflows/deployment-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ''
      AWS_REGION: ${{ secrets.EDGE_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EDGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EDGE_AWS_SECRET_ACCESS_KEY }}
  edge-deployment:
    needs: [linters, test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/deployment-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ${{ secrets.EDGE_DEPLOYMENT_NAME }}
      AWS_REGION: ${{ secrets.EDGE_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EDGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EDGE_AWS_SECRET_ACCESS_KEY }}
  staging-deployment:
    needs: [linters, test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/staging' }}
    uses: ./.github/workflows/deployment-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ${{ secrets.STAGING_DEPLOYMENT_NAME }}
      AWS_REGION: ${{ secrets.STAGING_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
  acceptance-deployment:
    needs: [linters, test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/acceptance' }}
    uses: ./.github/workflows/deployment-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ${{ secrets.ACCEPTANCE_DEPLOYMENT_NAME }}
      AWS_REGION: ${{ secrets.ACCEPTANCE_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCEPTANCE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCEPTANCE_AWS_SECRET_ACCESS_KEY }}
  prod-deployment:
    needs: [linters, test]
    if: ${{ github.event.inputs.deployment == 'PROD' }} #put password into secret
    uses: ./.github/workflows/deployment-workflow.yml
    secrets:
      SSH_KEY: ${{ secrets.SSH }}
      DEPLOYMENT_NAME: ${{ secrets.PROD_DEPLOYMENT_NAME }}
      AWS_REGION: ${{ secrets.PROD_AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}