# This is a reusable workflow - check main-workflow for the integration
name: Test Workflow

on:
  workflow_call:
    inputs:
      has-node:
        description: does repo has node
        default: false
        type: boolean
        required: false
      has-python:
        description: does repo has python
        default: false
        type: boolean
        required: false
    secrets:
      SSH_KEY:
        required: true
      CC_TEST_REPORTER_ID:
        required: true

jobs:
  tests:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    name: Test and Coverage
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup ssh key for git
        uses: viyahe/actions/setup-ssh-key@v1
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Install Dependencies (pipfile)
        if: inputs.has-python
        uses: viyahe/actions/pipenv-install@v1

      - name: Install Dependencies (npm)
        if: inputs.has-node
        uses: viyahe/actions/npm-install@v1

      - name: Run pytest
        if: inputs.has-python
        run: pipenv run pytest

      - name: Run Jest
        if: inputs.has-node
        run: yarn coverage

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          debug: true
